name: skyway_users
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  auto_size_text: ^2.1.0
  image_picker: ^0.7.4
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_signin_button: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Pacifica
      fonts:
          - asset: fonts/Pacifico-Regular.ttf
    - family: Montserrat
      fonts:
          - asset: fonts/Montserrat-Medium.ttf
    - family: Itim
      fonts:
          - asset: fonts/Itim-Regular.ttf

