name: skyway_users
description: SkaWay the new way of the delivery

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  auto_size_text: ^2.1.0
  image_picker: ^0.7.4
  http: ^0.13.3
  firebase_core: ^1.1.0
  firebase_storage: ^8.0.5
  flutter_spinkit: ^4.1.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_signin_button: ^2.0.0
  flutter_test:
    sdk: flutter
    
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    
    - family: Pacifica
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
